In [1]:
!nvidia-smi

Wed Sep 18 01:58:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import torch
print(torch.__version__)

2.4.0+cu121


### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Getting tensor back as int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [15]:
# Creating random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2062, 0.5869, 0.0127, 0.7394],
        [0.5653, 0.1378, 0.4287, 0.8697],
        [0.8905, 0.8033, 0.2285, 0.5895]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([3, 4])

In [18]:
# Creating a random tensor with similar shape of another tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.shape

torch.Size([224, 224, 3])

### Tensor of all zeroes

In [19]:
zeroes_tensor = torch.zeros(3,4)
zeroes_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeroes_tensor.ndim

2

In [21]:
zeroes_tensor.shape

torch.Size([3, 4])

### Tensor of all ones

In [22]:
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones_tensor.dtype

torch.float32

### Creating range of tensors

In [24]:
# Using torch.arange()
# torch.arange(start, end, step)

ones_to_100 = torch.arange(1, 100, 3)
ones_to_100

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52,
        55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

### Creating tensor-like

- To get a tensor with same same as some other tensor.
- It can be ones_like, zeros_like

In [25]:
ones_to_100_zeros = torch.zeros_like(ones_to_100)
ones_to_100_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

**Note:**
Issues in PyTorch and DL are of three types:
- Not the right data type
- Not the right shape
- Not the right device

In [26]:
# Float 32 tensor

float_32 = torch.tensor (
                          [3.0, 6.0, 9.0],
                          dtype=torch.float32,
                          device=None,
                          requires_grad=False # whether to track gradients of tensor or not
                        )
float_32

tensor([3., 6., 9.])

In [27]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_32 * float_16

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = float_32.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_32 * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

In [31]:
r_tensor = torch.rand(2,3,4)
r_tensor

tensor([[[0.3867, 0.6277, 0.1471, 0.5911],
         [0.8015, 0.5513, 0.2467, 0.8963],
         [0.9269, 0.2499, 0.7145, 0.6893]],

        [[0.2581, 0.3707, 0.2009, 0.7280],
         [0.3780, 0.6044, 0.0868, 0.0189],
         [0.8490, 0.3618, 0.2086, 0.7700]]])

In [32]:
r_tensor.shape, r_tensor.dtype, r_tensor.device

(torch.Size([2, 3, 4]), torch.float32, device(type='cpu'))

### Tensor operations

Common operations:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication


In [33]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [34]:
t+10

tensor([11, 12, 13])

In [35]:
t*10

tensor([10, 20, 30])

In [36]:
t-10

tensor([-9, -8, -7])

In [37]:
torch.mul(t, 10)

tensor([10, 20, 30])

In [38]:
t * t

tensor([1, 4, 9])

In [39]:
torch.matmul(t, t) # Matrix multiplication

tensor(14)

In [40]:
1*1 + 2*2 + 3*3

14

In [41]:
t @ t # matmul is more clearer though

tensor(14)

In [42]:
# inner dimensions must match

torch.matmul( torch.rand(3,2) , torch.rand(2,5) ), torch.matmul( torch.rand(3,2) , torch.rand(2,5) ).shape

(tensor([[0.8974, 0.5909, 0.7146, 0.7775, 0.3887],
         [0.4375, 0.2776, 0.3927, 0.3528, 0.1964],
         [0.9681, 0.5839, 0.9985, 0.7043, 0.4550]]),
 torch.Size([3, 5]))

In [43]:
# torch.matmul( torch.rand(3,2) , torch.rand(3,2) ) # won't work

### **Transposing a Tensor**

In [44]:
tens = torch.rand(3,4,5)
tens.shape

torch.Size([3, 4, 5])

In [45]:
tt = torch.rand(3,4)
tt.shape, tt.T.shape

(torch.Size([3, 4]), torch.Size([4, 3]))

In [46]:
tens.mT.shape # For multiple dimensional tensors

torch.Size([3, 5, 4])

In [47]:
tensor = torch.arange(1, 6)
tensor

tensor([1, 2, 3, 4, 5])

In [48]:
torch.mean(tensor.type(torch.float32))

tensor(3.)

In [49]:
torch.min(tensor)

tensor(1)

In [50]:
torch.max(tensor)

tensor(5)

In [51]:
torch.sum(tensor)

tensor(15)

### Finding the positional min and max

In [52]:
# Position of minimum value with argmin()
tensor.argmin()

tensor(0)

In [53]:
tensor.argmax()

tensor(4)

In [54]:
tensor[0]

tensor(1)

### Reshape, stacking, squeezing adn unsqueezing tensors

Rule:
- Reshaping - reshapes tensor into another defined shape
- View - return a view of an input tensor of certain shape but keep the same memory of the original tensor (If the values in view are changed, the priginal tensors value will also be changed, but the shape remains.)
- Stack - stacking tensors on top of each other or side by side
- Squeeze - removes all 1 dimension tensors from a multi dimenional tensors
- Unsqueeze - opposite of last one
- Permute - Return a view of the input with dimensions permuted in a certain way

In [55]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
# Adding extra dimensions
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# Changing the view
z = x.view(9, 1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [58]:
z[:, 0] = 5
z, x

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [59]:
x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [60]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0) # Vertically stacked
x_stacked

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [61]:
x_stacked = torch.stack([x, x, x, x], dim = 1) # Horizontally stacked
x_stacked

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [62]:
# Squeeze

xx = torch.rand(2,3)
xx

tensor([[0.3422, 0.8106, 0.3296],
        [0.6682, 0.9267, 0.9516]])

In [63]:
xx.squeeze() # Removes all single dimensions from the target tensor

tensor([[0.3422, 0.8106, 0.3296],
        [0.6682, 0.9267, 0.9516]])

In [64]:
x = xx.reshape(3,1,1,2)
x.shape

torch.Size([3, 1, 1, 2])

In [65]:
x.squeeze().shape

torch.Size([3, 2])

In [66]:
x.squeeze().shape

torch.Size([3, 2])

In [67]:
# Adds a single dimension
x.squeeze().unsqueeze(0).shape, x.squeeze().unsqueeze(1).shape, x.squeeze().unsqueeze(2).shape

(torch.Size([1, 3, 2]), torch.Size([3, 1, 2]), torch.Size([3, 2, 1]))

In [68]:
x = torch.rand(4,5,6)
x.shape

torch.Size([4, 5, 6])

In [69]:
x = x.permute(2,0,1)
x.shape

torch.Size([6, 4, 5])

In [70]:
x[0, 0, 0].item()

0.42480963468551636

### Indexing (Selecting Data in Tensors)

In [71]:
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
x[0][0], x[0, 0] # Both are not same

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [73]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [74]:
x[0, 2, 2]

tensor(9)

In [75]:
x[0, :, 2]

tensor([3, 6, 9])

### PyTorch tensors and NumPy

In [76]:
# Numpy Array to Tensor

import torch
import numpy as np

arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr)

arr, tensor # numpy default dtype is float64, unlike pytorch tensor which is float64

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
arr = arr + 1
arr, tensor # no change in tensor if numpy changed

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
# Tensor to NumPy

tensor = torch.arange(1., 11.)
numpy_arr = tensor.numpy()
tensor, numpy_arr # no change in numpy if tensor changed

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32))

### Reproducibilty
Trying to take random out of random

In [79]:
import torch

random_a = torch.rand(3, 4)
random_b = torch.rand(3, 4)

random_a, random_b, random_a == random_b # Highly unlikely that a will be equal to b

# So we need to seed this randomness

(tensor([[0.2460, 0.9840, 0.2252, 0.9166],
         [0.1705, 0.6889, 0.7004, 0.6052],
         [0.4985, 0.6122, 0.4990, 0.0222]]),
 tensor([[0.5061, 0.1798, 0.3669, 0.2033],
         [0.3384, 0.0201, 0.9290, 0.9664],
         [0.8674, 0.4028, 0.8399, 0.7680]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [80]:
RANDOM_SEED = 10


torch.manual_seed(RANDOM_SEED) # need to be used everytime we are using torch
random_a = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # need to be used everytime we are using torch
random_b = torch.rand(3, 4)

random_a, random_b, random_a == random_b

(tensor([[0.4581, 0.4829, 0.3125, 0.6150],
         [0.2139, 0.4118, 0.6938, 0.9693],
         [0.6178, 0.3304, 0.5479, 0.4440]]),
 tensor([[0.4581, 0.4829, 0.3125, 0.6150],
         [0.2139, 0.4118, 0.6938, 0.9693],
         [0.6178, 0.3304, 0.5479, 0.4440]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Using GPU's in PyTorch

In [81]:
import torch

!nvidia-smi # You know how to use it

Wed Sep 18 01:58:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [82]:
torch.cuda.is_available()

True

### Setting up device agnostic code

In [83]:
import torch

In [84]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [85]:
# Count number of devices
torch.cuda.device_count()

1

### Putting Tensors and models on GPU

In [86]:
import torch

tensor = torch.tensor([1,2,3,4,5,6])

tensor, tensor.device

(tensor([1, 2, 3, 4, 5, 6]), device(type='cpu'))

In [87]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3, 4, 5, 6], device='cuda:0'), device(type='cuda', index=0))

In [88]:
### If tensor is on GPU, can't tranform it to NumPy

tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3, 4, 5, 6])

# And we are done with the basics woohoooo!!!!

### Now, we will practice PyTorch workflow in another notebook